### PR TITLE
README.md: HTTP => HTTPS

### PR DESCRIPTION
**Pull request by Schweinepriester**
Checked the link, skipping the redirect HTTP => HTTPS this way 0:-)

### CODE REVIEW

**Review by micalevisk — APPROVED** [review]

**Comment by Schweinepriester** [comment]
But why closed? :o

**Comment by antonmedv** [comment]
I don’t know)

**Comment by Schweinepriester** [comment]
… want me to do anything, open another PR, or…?

**Comment by antonmedv** [comment]
Lets do it.

**Comment by Schweinepriester** [comment]
Et voilà, #302.

**Pull request closed without merging**
