### PR TITLE
Fix quote regex

### PR DESCRIPTION
**Pull request by xtutu**
match "-" should use "\\-"

### CODE REVIEW

**Comment by xtutu** [comment]
@googlebot I signed it!

**Comment by antongolub** [comment]
@xtutu,

Could you provide a test for the fix? To ensure that everything is ok with this regexp now.

**Comment by xtutu** [comment]
@antongolub 
image

is the code before seems want to match "-"? but it not correctly.

you can see the image i uploaded.

**Comment by antonmedv** [comment]
Please, try same with current regex we are using.

**Pull request closed without merging**
