### PR TITLE
solved issue #618

### LINKED ISSUE #618: zx --install do not install dependencies
## Expected Behavior
It should install all the dependencies that are included in the file, version 7.2.0 has no problem but version 7.2.2 installs nothing and show error

## Actual Behavior
```
$ node -v
v16.20.0
$ npm i zx --location=global
added 56 packages, and audited 57 packages in 5s
10 packages are looking for funding
$ zx -v
7.2.2
$ zx --install ./.deploy/deployer.mjs -e front
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-ssh' imported from /builds/......ployer.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:[75](https://gitlab.com/........139#L75):36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Version 7.2.0 has no such problems and the whole script works fine, I have not checked version 7.2.1 but it seems to me that it works, because the problems started to occur 4 days ago

## Specifications

- Version: 7.2.2
- Platform: node v16.20.0

### PR DESCRIPTION
**Pull request by ronitsharma03**
Fixes #618 Adding node-ssh dependency to the package.json

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR
- [ ] Types updated

### CODE REVIEW

**Comment by ronitsharma03** [comment]
@antonmedv Was it not the right method to do so. I am a beginner can you please ?

**Comment by ronitsharma03** [comment]
@antonmedv Would you please assign it to me ! I want to work on this issue!

**Comment by antonmedv** [comment]
https://github.com/webpod/webpod

**Comment by ronitsharma03** [comment]
@antonmedv What does this mean ?

**Comment by antonmedv** [comment]
zx already supports ssh via webpod.

**Pull request closed without merging**
