### PR TITLE
docs: add table of contents

### PR DESCRIPTION
**Pull request by antongolub**
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by antonmedv** [comment]
GitHub readne already have toc hiden by bamburger.

**Comment by antongolub** [comment]
But npmjs has not. Many ppl read the docs there.

**Comment by antonmedv** [comment]
Hmm, let me think 🤔

**Comment by antonmedv** [comment]
It looks way to big) Let's find something else. Half of people read doc on github and here toc is present.

**Pull request closed without merging**
