### PR TITLE
feat: export pkg version as const, add some tests for index

### PR DESCRIPTION
**Pull request by antongolub**
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [x] Tests pass

### CODE REVIEW

**Comment by antonmedv** [comment]
What about requre(zx/package.json)?

**Comment by antongolub** [comment]
`require` is a legacy workaround. But modern `import` does not load JSON by default (--experimental-json-modules).

**Comment by antonmedv** [comment]
https://github.com/google/zx#require

**Comment by antongolub** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-require-imports.md

**Comment by antongolub** [comment]
I agree with [Sindre](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c): we should completely abandon es5/cjs.

**Comment by antonmedv** [comment]
I also agree. But I don't think version constant is needed as it already in the package and the use case is really limited.

**Comment by antongolub** [comment]
It's just a "best practice" for utils.
https://lodash.com/docs/4.17.15#VERSION

**Comment by antongolub** [comment]
Ok, let's remove `version` from the global scope, but in-index.mjs ref is useful.

**Comment by antonmedv** [comment]
What other use case? Only check if script have ver requirements?

**Comment by antongolub** [comment]
Or to check, that current version is the latest: https://github.com/antongolub/yarn-audit-fix/blob/master/src/main/ts/stages.ts#L54

**Comment by antonmedv** [comment]
I think it can be easily done using fs.readJson as now fs-extra is used. Or via $’cat package.json’

**Comment by antongolub** [comment]
But not quite. We need to obtain `zx` pkg root (it does not always match to <cwd>/node_modules)

**Comment by antonmedv** [comment]
It’s true. Let me think more about it, naming, etc.

**Comment by antongolub** [comment]
Expose `import.meta.url` instead?

**Comment by antonmedv** [comment]
On adding version as export const.

**Comment by antonmedv** [comment]
Let not introduce a version. Usually zx installed in project dir, and package.json already have a version.

**Pull request closed without merging**
