### PR TITLE
Markdown cli:

### PR DESCRIPTION
**Pull request by tomek7667**
Markdown cli:
- Replace raw strings in code with an enum

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR (Not needed)
- [ ] Types updated

### CODE REVIEW

**Comment by antonmedv** [comment]
Nope.

**Comment by tomek7667** [comment]
Why?

**Comment by antonmedv** [comment]
What’s purpose of this enum?

**Comment by tomek7667** [comment]
In order to avoid typos in raw string for future, I believe not all of the markdown features were implemented yet. I think it also improves the code readability

**Comment by antonmedv** [comment]
> avoid typos in raw string for future

A simple union will be enough here. 

> it also improves the code readability

It is not.

**Comment by tomek7667** [comment]
| It is not.
Why not? In my opinion it's easier to read the code using complete words and by the way getting an information of what kind of it is. For example you would read such code: "this will happen in case of Markdown state corresponding to Javascript" - while just "js" is not as informative a better to read.

About the union type, I agree it would be enough, however it wouldn't support such nice autocompletion as the enum and the lesser readability I've mention above will remain. 

Thanks for responding, I just want to help :)

**Comment by antonmedv** [comment]
>wouldn't support such nice autocompletion as the enum

It will. VScode and idea works well. 

About readability: set state to markdown state root VS set state to root. 

Less words usually are better for readability.

**Comment by tomek7667** [comment]
Ok, thanks for the reply I will keep that in mind 😄

**Pull request closed without merging**
