### PR TITLE
this project is an affront to God and all who hold Jesus in their heart will seek to destroy it

### PR DESCRIPTION
**Pull request by smidgedy**
javascript was a mistake, this is a mistake

### CODE REVIEW

**Comment by smidgedy** [comment]
@googlebot I signed it!

**Comment by kungfooman** [comment]
There is one royal law in the bible: `Thou shalt love thy neighbor as thyself.`

By the sheer will of destroying this project, you are disrespecting a fractal of god. God wants this to exist, otherwise it wouldn't.

You should clear your soul from all hate and destructive feelings.

**Comment by mtimofiiv** [comment]
@kungfooman maybe that's the point. Maybe by destroying this project, he seeks to destroy himself, and all of us. Perhaps it's not javascript or `zx` that's the mistake, it's humanity?

**Comment by kungfooman** [comment]
> @kungfooman maybe that's the point. Maybe by destroying this project, he seeks to destroy himself, and all of us. Perhaps it's not javascript or `zx` that's the mistake, it's humanity?

Yes, clearly a fractal of god wants to destroy another fractal of god. Maybe we are onto a glitch in the universal mind of god. I am not sure if a destructive PR is enough to fix this issue with humanity.

There needs to be a circuit breaker against destruction. Fractals of god would need to stop destroying other fractals of god. And learn to accept. It's a hard problem.

**Comment by mtimofiiv** [comment]
Yes, agreed @kungfooman, this might be a strange place to start if the ultimate goal is universal destruction, or anything else for that matter.

There's also the possibility that @smidgedy is in fact God, and has chosen this method to attack the fragile fractal tree of its own creation. Perhaps, as this leaf of the fractal shatters, it will emit some kind of perfectly pitched vibration that ultimately culminates in full, encompassing destruction.

Perhaps, if @smidgedy is God, and seeks its own destruction, it is only capable of doing so by a reverse cascade that ultimately leads itself to the suicide of God itself.

**Comment by kungfooman** [comment]
> Yes, agreed @kungfooman, this might be a strange place to start if the ultimate goal is universal destruction, or anything else for that matter.
> 
> There's also the possibility that @smidgedy is in fact God, and has chosen this method to attack the fragile fractal tree of its own creation. Perhaps, as this leaf of the fractal shatters, it will emit some kind of perfectly pitched vibration that ultimately culminates in full, encompassing destruction.
> 
> Perhaps, if @smidgedy is God, and seeks its own destruction, it is only capable of doing so by a reverse cascade that ultimately leads itself to the suicide of God. We are fortunate to bear witness.

Good point @mtimofiiv, as the structure of space time disentangles before our eyes starting from the destructive fractals, there will be a quick-witted JavaScript hacker writing a one-liner in `zx` which ties everything back together, rescuing only the good networks.

The destructive fractals will float around in space time structure fragments with a broken time dimension, to sulk in their hate for the rest of the universal existence - in always the same infinite loop.

**Comment by devec0** [comment]
The warnings signs were all there, and we would be fools to ignore them. As NET.GOD advances their will, it is our purpose to simply merge it. Is their will to destroy the universe, or is God merely a technology purist who wishes to smite yet another Javascript tool, a Javascript tool built too early for humanity to comprehend it? Yes, that's it! God wishes to protect us from ourselves, being a kind and malevolent god, knowing that we were in fact created flawed - flawed and not yet ready to receive a pure Javascript re-implementation of bash.

The only god-fearing act is to respect the ominous green glow of the "approve" button, which at this point, has become the ultimate truth and the death of the universe. I bet the UX team at GitHub never saw that coming.

**Comment by ludwigschubi** [comment]
what is this pr smoking

**Comment by smidgedy** [comment]
```js
let count = parseInt(await $`ls -1 | wc -l`)
console.log(`Files count: ${count}`)
```

hmm way simpler than
```sh
count=$( ls -1 | wc -l)
echo "Files count: ${count}"
```

oh but wow look at the power of js to run stuff in parallel
```js
let hosts = [...]
await Promise.all(hosts.map(host =>
  $`rsync -azP ./src ${host}:/var/www`  
))
```

nah bruh that functional programming syntactic sugar with the promises framework is a godsend you can't even do parallel jobs in bash
```sh
hosts=(...)
parallel rsync -azP ./src {}:/var/www ::: ${hosts[@]}
```

THIS IS REAL "JAVASCRIPT" DONE BY REAL JAVASCRIPT DEVELOPERS. THEY HAVE PLAYED US FOR FOOLS

**Comment by antonmedv** [comment]
> parallel rsync -azP ./src {}:/var/www ::: ${hosts[@]}

This is exactly why `zx` exists. ;) 

Why do you prefer `parallel` instead of nodejs? Why to install parallel and not nodejs? Try use vanilla bash to collect exit codes for a few processes started in parallel?

**Comment by ludwigschubi** [comment]
@smidgedy I actually feel you dude, but there is no point in putting effort into stopping what other people think they need.
Live and let live and if somebody wants to run in circles with JavaScript, why let it bother you? Insisting that you are correct is rarely worth it

**Comment by smidgedy** [comment]
just tell the maintainers to merge the PR and we can all get on with our lives.

**Comment by ludwigschubi** [comment]
Ignorance is bliss my friend ... take the blue pill

**Comment by cate554** [comment]
Meow.

**Comment by Eebru-gzy** [comment]
Y'll think this dude really wants to destroy this job???? All I see sarcasmmmmm

**Comment by smidgedy** [comment]
Your engineers were so preoccupied with whether or not they could, they didn’t stop to think if they should.

**Review by lodenrogue — APPROVED** [review]
LGTM

**Comment by smidgedy** [comment]
Bless you, truly doing the Lord's work. If someone with write access could kindly complete the simple merge we can all be on our way.

**Comment by antonmedv** [comment]
Thanks for your PR, but as we not planning to delete the project this PR can't be merged. You can fork the project and continue development there by merging this PR.

**Comment by procedural** [comment]
This is what happens when you program in javascript.

**Comment by smidgedy** [comment]
bless you

**Comment by LintonAchmad** [comment]
May the odds forever be in your favor.

**Pull request closed without merging**
