### PR TITLE
perf: bundle zx package

### LINKED ISSUE #50: Bundle zx package
Currently installing `zx` package, costs `~125 files` and `832K` of disk space (401K reported by [packagephobia](https://packagephobia.com/result?p=zx)). Also, it is making zx dependant on `node_modules`. 

By bundling zx package:

- Install cost will be reduced to few files (basically one `zx.mjs`) and `~92KB` as of `v1.2.2`
- `zx` script will be standalone. Can possibly help #25 for embedded solutions or selfupdate
- Using rollup plugins, we can have a chance for deno build from same source (#24)
- Memory footprint will be reduced as a benefit from tree-shaking unused imports (quick test max RSS from `44580kb` to `37628kb` for `test.mjs`
- Easier dist analyzes 
- Possibility to use typescript
- Removing need of cjs hack for importing `version` from `package.json`

PR: #51

### PR DESCRIPTION
**Pull request by pi0**
Fixes #50 (see issue for merits) -- shall be closed if #50 is not accepted

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

Changes: 
- Adding rollup dependencies and `rollup.config.js`
- Moved all `dependencies` to `devDependencies` (bundled)
- (chore) sorted with `npx sort-package-json`
- Add `prepack` script to build before publish as well as before running tests
- ~~Move `index.mjs` and `zx.mjs` to `src/` -- ideas welcome if you prefer another struct~~
- Bundle into `dist`
- Add `exports` field

Remarks: `index.mjs` and `zx.mjs` are built standalone to allow distributing `zx` as single file yet keep supporting `import 'zx'`

### CODE REVIEW

**Review by lodenrogue — APPROVED** [review]

**Review by capaj — APPROVED** [review]

**Comment by antonmedv** [comment]
Again, why do we need to bundle things? 

What is the difference between install speed bundles vs source?

**Comment by pi0** [comment]
Install speed is indeed also improved. I've tried to explain the reasons in #50.

**Comment by pi0** [comment]
Closing as of discussions in #50.

**Pull request closed without merging**
