### PR TITLE
fix: add the "@" and ":" regex for quote

### PR DESCRIPTION
**Pull request by Mintnoii**
I want to use ZX to run some code like this:
```
const testRepo = "git@github.com:user/repo.git"
await $`git clone ${testRepo}`
```
But I got ` git clone $'git@github.com:user/repo.git'` 
So I want to add `@` and `:` to the regex of quote.

### CODE REVIEW

**Comment by antonmedv** [comment]
The 

    git clone $'git@github.com:user/repo.git'

And 

    git clone git@github.com:user/repo.git

Are the same. This regexp only for beautyfing .

**Comment by Mintnoii** [comment]
> The
> 
> ```
> git clone $'git@github.com:user/repo.git'
> ```
> 
> And
> 
> ```
> git clone git@github.com:user/repo.git
> ```
> 
> Are the same. This regexp only for beautyfing .

Thanks for your reply, but I still have a problem dealing with git address.I'm looking forward to your help.
When I try to clone a Git repository (repository address written in a variable)
```
 let zxUrl = 'git@github.com:google/zx.git'
 await $`git clone ${zxUrl}`
```
The console reported an error:
image
After I changed the `quote` method in the `node_modules\zx\build\util.js` file, I tried again
image
Then I can successfully download the corresponding repository code.
image

**Comment by antonmedv** [comment]
Yes, looks like your shell is not bash. Probably zx needs a warning and automatically disable quotation function.

**Comment by Mintnoii** [comment]
The terminal I use is the bash configured in vscode. Take the liberty to ask. Since this regex is just to beautify the output, can you merge pr and add these two symbols? So far it seems that adding `@` and `:` can handle this scenario.

**Comment by antonmedv** [comment]
No, I will not merge this PR. As this is not the problem in the zx code. 

A proper solution should be used. For some reason you shell in zx is not bash. 

Try to update to zx 7.0.7. One issue with misconfiguration was fixed there.

**Pull request closed without merging**
