### PR TITLE
Readme update: Adds no install method of running the script

### PR DESCRIPTION
**Pull request by a7ul**
> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

Currently using zx with https://github.com/a7ul/undercover 
and noticed that we can run it on target machines without installing it directly.

### CODE REVIEW

**Comment by antonmedv** [comment]
I don't think we want this to be in README.md. What do you think @kruil?

**Comment by itsnotlupus** [comment]
An alternate mean of running without install would be to have this be the first line of a script

`#!/usr/bin/env -S npx zx`

**Comment by antonmedv** [comment]
This `-S` option is not widely available.

**Comment by antonmedv** [comment]
And I think everybody who knows `npx` will be using it. Others just need to npm i -g zx 😝

**Comment by antongolub** [comment]
Just a remark: `npm_config_yes=true npx zx` / `yes | npx zx` for npm v7

**Pull request closed without merging**
