### PR TITLE
Convert project to work with Bun

### PR DESCRIPTION
**Pull request by DaniGuardiola**
Work in progress...

### CODE REVIEW

**Comment by DaniGuardiola** [comment]
My bad, I didn't mean to create the PR on this repo, I wanted to do it on mine. Sorry for the noise.

**Comment by antongolub** [comment]
Hey @DaniGuardiola,

Just FIY, we are also doing some work to make the zx work with the bun (this mostly concerns zx dependencies and runtime apis they use): 
* https://github.com/oven-sh/bun/pulls?q=is%3Apr+is%3Aclosed+author%3Aantongolub
* https://github.com/qiwi/zx-extra/blob/master/package.json#L14

So _maybe_ zx is compatible with bun >=1.0.14

**Comment by ivancuric** [comment]
There seems to be a built-in alternative now:
https://bun.sh/blog/the-bun-shell

**Comment by DaniGuardiola** [comment]
@ivancuric yep.

Funny story, I created this fork the same day the Jarred tweeted about $ lol.

**Comment by antongolub** [comment]
Anyway, zx seems to be compatible with bun now: https://github.com/google/zx/pull/752

**Pull request closed without merging**
