### PR TITLE
Muted question()

### LINKED ISSUE #521: How to use `question` without feedback
## Expected Behavior
I'd like to be able to use the `question()` function add when I type, nothing appears, similar to `read -s`.

## Actual Behavior
It seems like this isn't possible today, all you can do is specify choices, no other options.

## Steps to Reproduce the Problem
```
question('Enter super private information: ');
```

## Specifications

- Version: 7.0.8
- Platform: MacOS 12.6, Node 18.9

### PR DESCRIPTION
**Pull request by cyntler**
Fixes #521 

This PR extends the `question()` function a bit by allowing it to be passed the `muted` and `mutedCharacter` options.
This allows the user to hide the input they are typing.

- [X] Tests pass
- [X] Appropriate changes to README are included in PR
- [x] Types updated

### CODE REVIEW

**Comment by cyntler** [comment]
@antonmedv Could you please approve this PR for workflows run?

**Comment by antonmedv** [comment]
I'm still thinking about the solution. Maybe include https://www.npmjs.com/package/read instead.

**Comment by cyntler** [comment]
Ok, I understand. I thought about using this package but the last release was 7 years ago, it made me a bit discouraged. Additionally, there are still issues which say that silent doesn't quite work as it should.

**Comment by antonmedv** [comment]
Will check issues

**Review by cleverhare — APPROVED** [review]
It looks good now

**Comment by cyntler** [comment]
@cleverhare Conflicts resolved.

**Comment by cyntler** [comment]
@antonmedv @cleverhare Can we merge this request?

**Comment by antonmedv** [comment]
Sure. Let me review it one more time.

**Comment by cleverhare** [comment]
yes you can merge it now

**Review by cleverhare — APPROVED** [review]
Looks Good

**Comment by logeshswell** [comment]
@cyntler Can you merge your changes?

**Comment by cleverhare** [comment]
Yes it is absolutely okay to get merged

**Comment by RMEngels** [comment]
@antonmedv will this PR still get implemented? Seems like it's closed without any other message? Unless I'm missing something?

**Comment by antonmedv** [comment]
I think this complicates question() func . It is better suited for a separate package. WDYT?

**Comment by RMEngels** [comment]
Sound fine to me :thum

**Pull request closed without merging**
