### PR TITLE
Fix redundant line feed output

### LINKED ISSUE #89: a newline at the end of the output line
I use `zx` to build a script program, script code example:
```js
#!/usr/bin/env node

import { $ } from 'zx'
$.verbose = false

async function log(message) {
  const now = await $`date '+%Y-%m-%d %H:%M:%S'`
  console.log(`[${now}]===========${message}============`)
}

log('env')
log(`node version ${await $`node -v`}`)
log(`npm version ${await $`npm -v`}`)
```
## Expected Behavior
My expectation is like this.
```txt
[2021-05-17 14:41:42]===========env============
[2021-05-17 14:41:42]===========node version v14.17.0============
[2021-05-17 14:41:42]===========npm version 6.14.13============
```
## Actual Behavior
But, i got this result
```txt
[2021-05-17 14:57:08
]===========env============
[2021-05-17 14:57:08
]===========node version v14.17.0
============
[2021-05-17 14:57:08
]===========npm version 6.14.13
============
```
## Steps to Reproduce the Problem
1. execute `zx index.mjs` in a shell

## Specifications
I think there is a `\n` at the end of the line of the standard output.

- Version: node v14.17.0
- Platform: macOS

### PR DESCRIPTION
**Pull request by hubvue**
Fixes #89 

> This PR is a fix to the #89 problem

- [x] Tests pass

### CODE REVIEW

**Comment by hubvue** [comment]
@googlebot I signed it!

**Comment by antonmedv** [comment]
Let’s not modify output of commands.

**Comment by hubvue** [comment]
@antonmedv In this case, i can only write a function to delete the end of the line. That's what I do now. Do you have any good suggestions?
```js
async function shell(command) {
  const cmdRes = await $(command)
  return cmdRes.toString().replace(/\n$/, '')
}
```

**Comment by antonmedv** [comment]
```js
async function log(message) {
  const now = await $`date '+%Y-%m-%d %H:%M:%S'`
  console.log(`[${now.stdout.trim()}]===========${message}============`)
}
```

It's better to not modify the output of programs. It's easy to do on the user side.

And zx is smart enough to detect what here newline should be omitted during command substitution:

```js
let branch = await $`git branch --show-current`
await $`dep deploy --branch=${branch}`
```

**Comment by hubvue** [comment]
Thanks, this PR and #89  can be closed.

**Pull request closed without merging**
