### PR TITLE
Added --help, --quiet and --shell

### LINKED ISSUE #16: Set verbosity and shell via command line flags
## Expected Behavior

- `-V` to turn off verbose output
- `-s SHELL` to set which shell to use.

and `--help` and `--version` while we're at it lol

## Actual Behavior
```
$ zx -h
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/maxtimkovich/notes/-h' imported from /Users/maxtimkovich/.asdf/installs/nodejs/14.16.0/.npm/lib/node_modules/zx/zx.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///Users/maxtimkovich/.asdf/installs/nodejs/14.16.0/.npm/lib/node_modules/zx/zx.mjs:51:18
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### PR DESCRIPTION
**Pull request by FarazzShaikh**
Closes #16 

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

## Adds 3 more options and refines argv handling.

| option | Description |
|--------|-------------|
| `-h, -H, --help` | Print usage |
| `-q, -Q, --quiet` | Run with [`$.verbose`](#verbose) set to `false`|
| `-s, -S, --shell` | Specify [`$.shell`](#shell) |

If `test.mjs` contains the following:
```bash
console.log((await $`echo $0`).stdout);
```
Standard:
```bash
zx ./test.mjs
# Result
$ echo $0
/bin/bash
/bin/bash
```

Use other shell:
```bash
zx -s zsh ./test.mjs
# Result
$ echo $0
/usr/local/bin/zsh
/usr/local/bin/zsh
```

Run with `$.verbose = false` using zsh:
```bash
zx -q -s zsh ./test.mjs
# Result
/usr/local/bin/zsh
```

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
@antonmedv what do you think?

**Comment by ristomatti** [comment]
After experimenting with `zx` for a moment, the first thing that felt quite unintuitive to me was that something like this prints anything to stdout:

```js
let files = await $`ls`
```

At least to me it felt like an unexpected "side effect". After learning about `$.verbose = false`, I realized I would want to have this flag on pretty much every script. This made me wonder why `false` is not the default :thinking:.

I realize changing the default in this case would not be a sensible option, so something like a `--quiet` flag would be the second best option. :+1:

**Comment by FarazzShaikh** [comment]
I am not sure why this PR has been ignored for so long.

@antonmedv i can bring this back up to work with the last ear version of the repo if you’d like.

**Comment by ristomatti** [comment]
@FarazzShaikh FYI: I noticed you've used double quotes while the rest of the code appears to use single quotes. Just pointing this out so nobody else has to.

**Comment by FarazzShaikh** [comment]
@ristomatti Thank you! I'll change that while I am updating the code. That is, if there's interest in merging this PR.

**Comment by antonmedv** [comment]
I’m thinking about bringing in minimist. So it can be used instead.

**Comment by FarazzShaikh** [comment]
Sounds good, should I rewrite this PR using Minimist or open a new one?

**Comment by justinasfour04** [comment]
--shell=/usr/bin/zsh is not working
image
image

**Comment by justinasfour04** [comment]
@FarazzShaikh

**Comment by FarazzShaikh** [comment]
@justinasfour04 this PR was closed and is not on my radar to debug. Sorry.

**Comment by justinasfour04** [comment]
@FarazzShaikh it worked, just needed to put the --shell= before the file path.

**Pull request closed without merging**
