### PR TITLE
Add --allowUnauthorized CLI arg to ignore SSL cert issues

### PR DESCRIPTION
**Pull request by midzelis**
This add a new argument to allow self-signed and other invalid SSL certificate. 

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by midzelis** [comment]
@googlebot I signed it!

**Comment by antonmedv** [comment]
For this case better to use curl:

curl … | zx

Thr zx can take stdin as input script.

**Comment by midzelis** [comment]
> For this case better to use curl:
> 
> curl … | zx
> 
> Thr zx can take stdin as input script.

Using curl... | zx will not allow you to pass additional CLI parameters to your script.

**Comment by antonmedv** [comment]
I see. So I think this is a problem we need to fix.

**Comment by antonmedv** [comment]
Now it works.

**Pull request closed without merging**
