### PR TITLE
fix: make internal npx invocation compatible with npm v6

### PR DESCRIPTION
**Pull request by antongolub**
https://omrilotan.medium.com/npx-breaking-on-ci-b9f3f61d4676

relates https://github.com/google/zx/commit/0cf9b9dc92c28f59f25e3db81c62846c37bcef82

- [x] Tests pass

### CODE REVIEW

**Comment by antonmedv** [comment]
I didn't get it. So npm@6 will not work as it not supports --yes? But npm@7 and npm@6 both supports `npm_config_yes`?

**Comment by antongolub** [comment]
**npm@6** just ignores `npm_config_yes`, but **npm@7** uses env value as `--yes` param alias.

**Comment by antonmedv** [comment]
> npm@6

But npm@6 will ask for user input? And fail?

**Comment by antongolub** [comment]
npm@6 does not emit prompt. This feature was added in v7

**Pull request merged**
