### PR TITLE
Using file:/// for loading files using absolute path

### PR DESCRIPTION
**Pull request by bsnux**
Using file:/// for loading files using absolute path

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by bsnux** [comment]
@googlebot I fixed it

**Comment by bsnux** [comment]
@googlebot I fixed it.

**Comment by bsnux** [comment]
@googlebot I fixed it

**Comment by antonmedv** [comment]
So what is use case, what this is needed?

**Comment by antonmedv** [comment]
I get what it does, but why? Why not add `foobar:///` prefix?

**Comment by antonmedv** [comment]
Try to remove file:// from file name.

**Comment by bsnux** [comment]
These ones are not working:

```
zx /tmp/scripts/a.mjs
```

```
zx //tmp/scripts/a.mjs
```

**Comment by bsnux** [comment]
The original code is doing this

```
await import(join(process.cwd(), firstArg))
```

My understanding is that will use the current working directory plus the name of the file passed as argument. 

Am I missing something?

**Comment by SilurianYang** [comment]
(#28) There is a description of related issues here

**Comment by antonmedv** [comment]
Got it! Fixed,

**Pull request closed without merging**
