### PR TITLE
test: http requires CR LF breaks

### PR DESCRIPTION
**Pull request by kapouer**
nodejs 18 has a strict parser which otherwise fails on this test.

- [x] Tests pass

### CODE REVIEW

**Comment by antonmedv** [comment]
Something seems not right.

**Comment by kapouer** [comment]
Yes i probably need to write those control characters outside github

**Comment by antonmedv** [comment]
Fixed in #486

**Comment by kapouer** [comment]
Isn't this a mistake ? I don't see how #486 is related ?

**Comment by antonmedv** [comment]
Looks like it was fixed. Check files, please.

**Pull request closed without merging**
