### PR TITLE
Add minute support in duration (#703)

### LINKED ISSUE #703: Feature request: support "minutes" for duration
How about supporting something like this ?

## Expected Behavior

```ts
import 'zx/globals'
await $`sleep 2m`.timeout("1m")
```

## Actual Behavior

```
Error: Unknown duration: "1m".
```

### PR DESCRIPTION
**Pull request by RezaKargar**
This fixes #703 

I also added test related to the change.

### CODE REVIEW

**Review by servusdei2018 — APPROVED** [review]

**Comment by antongolub** [comment]
Hey, @RezaKargar,

`type Duration` should be updated too.

**Comment by RezaKargar** [comment]
Thanks @antongolub, It's done.

**Comment by antongolub** [comment]
Seems good. Rebase plz.

**Comment by RezaKargar** [comment]
Dear @antongolub, I rebased the branch.

**Comment by RezaKargar** [comment]
Hey @antonmedv, I fixed the prettier issue.

**Review by antonmedv — APPROVED** [review]

**Comment by RezaKargar** [comment]
Tests fixed too.
@antonmedv

**Review by antongolub — APPROVED** [review]

**Comment by perrinjerome** [comment]
Nice, thanks

**Pull request merged**
